# Generated by Django 4.2 on 2024-04-02 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Название')),
                ('author', models.CharField(max_length=250, verbose_name='Автор')),
                ('info', models.TextField(max_length=1000, verbose_name='Описание')),
                ('longitude', models.CharField(max_length=100, verbose_name='Широта')),
                ('latitude', models.CharField(max_length=100, verbose_name='Долгота')),
            ],
            options={
                'verbose_name': 'Объект',
                'verbose_name_plural': 'Объекты',
            },
        ),
        migrations.CreateModel(
            name='ObjectType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Тип объекта',
                'verbose_name_plural': 'Типы объектов',
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Викторина',
                'verbose_name_plural': 'Викторины',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=100, verbose_name='Текст вопроса')),
                ('image', models.ImageField(upload_to='questions_images', verbose_name='Изображение вопроса')),
                ('image_base64', models.CharField(blank=True, max_length=500, verbose_name='base64 кодировка фотографии')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='summer_garden.quiz', verbose_name='Викторина')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
            },
        ),
        migrations.CreateModel(
            name='ObjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='objects_images', verbose_name='Изображение объекта')),
                ('image_base64', models.CharField(blank=True, max_length=500, verbose_name='base64 кодировка фотографии')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='summer_garden.object', verbose_name='Объект')),
            ],
            options={
                'verbose_name': 'Изображение объекта',
                'verbose_name_plural': 'Изображения объектов',
            },
        ),
        migrations.AddField(
            model_name='object',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='summer_garden.objecttype', verbose_name='Тип'),
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=100, verbose_name='Текст ответа')),
                ('right', models.BooleanField(verbose_name='Правильный ответ')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='summer_garden.question', verbose_name='Вопрос')),
            ],
        ),
    ]
