# Generated by Django 4.2 on 2024-04-02 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summer_garden', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'verbose_name': 'Ответ', 'verbose_name_plural': 'Ответы'},
        ),
        migrations.AlterField(
            model_name='answer',
            name='text',
            field=models.TextField(max_length=300, verbose_name='Текст ответа'),
        ),
        migrations.AlterField(
            model_name='objectimage',
            name='image_base64',
            field=models.TextField(blank=True, verbose_name='base64 кодировка фотографии'),
        ),
        migrations.AlterField(
            model_name='question',
            name='image_base64',
            field=models.TextField(blank=True, max_length=500, verbose_name='base64 кодировка фотографии'),
        ),
    ]
