# Generated by Django 4.2.11 on 2024-05-20 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summer_garden', '0003_alter_answer_question_alter_object_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='latitude_conv',
            field=models.CharField(default=str, max_length=100, verbose_name='Конвертированная широта'),
        ),
        migrations.AddField(
            model_name='object',
            name='longitude_conv',
            field=models.CharField(default=str, max_length=100, verbose_name='Конвертированная долгота'),
        ),
    ]
